version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "npm install && jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll